name: Lint and Test

# Controls when the action will run.
on:
    push:
        branches: [main]
    pull_request:
        branches: ["**"]

jobs:
    lint:
        name: Lint job
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./service

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version-file: "./service/.python-version"

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Static analysis
              run: uv run mypy ./src

            - name: Linting
              run: |
                  uv run ruff check ./src
                  uv run ruff format --check ./src

    test:
        name: Test job
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./service

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version-file: "./service/.python-version"

            - name: Install the project
              run: uv sync --all-extras

            - name: Testing
              run: |
                  uv run pytest tests
