name: Service Lint

# Controls when the action will run.
on:
    push:
        branches: [main]
    pull_request:
        branches: ["**"]

jobs:
    lint-typecheck:
        name: python
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./service

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Static analysis
              run: mypy .

            - name: Linting
              run: |
                  ruff check
                  ruff format --check
